name: Lifesteal
version: '1.0-SNAPSHOT'
main: site.thatkid.lifesteal.Lifesteal
api-version: '1.21'

permission:
  lifesteal:
    description: Allows you to use lifesteal commands
    default: op

commands:
    lifesteal:
        description: Main lifesteal command
        permission: lifesteal
    drain:
      description: Drain a heart
    revive:
      description: Revive a player banned from heart loss

authors: [ ThatKid ]
website: thatkid.github.io
