name: Lifesteal
version: '1.0-SNAPSHOT'
main: site.thatkid.lifesteal.Lifesteal
api-version: '1.21'

permission:
  lifesteal:
    description: Allows you to use lifesteal commands
    default: op

commands:
    lifesteal:
        description: Main lifesteal command
        permission: lifesteal
    drain:
      description: Drain a heart

libraries:
    - "net.axay:kspigot:1.21.0"

authors: [ ThatKid ]
website: thatkid.github.io
